devices:
  - name: bat-1
    type: bat
    addr: ":5025"
    time_scale: 60
    noise:
      seed: 1440
      delay:
        mode: always
        value: 100ms
      garbage:
        mode: chance
        chance: 0.05
      silence:
        mode: chance
        chance: 0.05
      break:
        mode: on_command
        n: 30
      truncate:
        mode: chance
        chance: 0.05
        cut_at: 5
    params:
      capacity: 2
      empty_level: 3
      full_level: 4.2
      draw: 1